# Generated by Django 5.1.3 on 2024-11-11 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_last_login_users_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('7ff0d447-b20d-44e1-a395-2f8f0cdb971b'), unique=True),
        ),
    ]
