# Generated by Django 5.1.3 on 2024-11-12 03:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_verification_code_alter_users_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_verify',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('4792be08-103f-43be-aed0-4089117a537e'), unique=True),
        ),
    ]
