# Generated by Django 5.1.3 on 2024-11-12 04:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_users_is_verify_alter_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('b34bec96-cd89-41f8-8e95-b086a20a2552'), unique=True),
        ),
    ]
