# Generated by Django 5.1.3 on 2024-11-12 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('58ab2404-f0d4-4e12-8272-a1aa25b051f0'), unique=True),
        ),
    ]
