# Generated by Django 5.1.3 on 2024-11-12 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_card_transaction_card_id_alter_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('5e89b1a7-6c4a-485c-af0e-f487ce5c7796'), unique=True),
        ),
    ]
