# Generated by Django 5.1.3 on 2024-11-12 18:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_cards_balance_alter_users_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='is_payment_enabled',
        ),
        migrations.RemoveField(
            model_name='merchantcategory',
            name='is_payment_enabled',
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('b80c5ea6-0347-469e-91f0-8b108e225976'), unique=True),
        ),
    ]
