# Generated by Django 5.1.3 on 2024-11-12 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_merchant_is_payment_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('3ec8688b-7cdd-4acb-9739-cd07717a8fbb'), unique=True),
        ),
    ]
